# Generated by Django 3.1.3 on 2020-11-12 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoshandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='user',
            field=models.ForeignKey(limit_choices_to=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
